services:
  learnsql-database:
    image: postgres:16.4
    container_name: learnsql-database
    profiles: [ db ]
    networks:
      - learnsql-network
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=bookstore
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    tty: true
    cpu_count: 2
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  learnsql-database-migrations:
    image: ghcr.io/emilpriver/geni:v1.1.5
    container_name: learnsql-database-migrations
    profiles: [ db ]
    depends_on:
      learnsql-database:
        condition: service_healthy
        restart: true
    networks:
      - learnsql-network
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@learnsql-database:5432/bookstore
    volumes:
      - ./migrations:/migrations
    command: up

networks:
  learnsql-network:

volumes:
  postgres_data:
