
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- EXTENSIONS 

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- TABLES 

CREATE TABLE books (
 created_at timestamp with time zone ,
 genre character varying (50),
 id uuid  NOT NULL,
 isbn character varying (13) NOT NULL,
 price numeric  NOT NULL,
 stock_quantity integer ,
 title character varying (255) NOT NULL,
 updated_at timestamp with time zone 
);

CREATE TABLE sales (
 book_id uuid ,
 created_at timestamp with time zone ,
 id uuid  NOT NULL,
 isbn character varying (13) NOT NULL,
 payment_method character varying (10) NOT NULL,
 quantity integer  NOT NULL,
 status character varying (15),
 total_price numeric  NOT NULL,
 updated_at timestamp with time zone 
);

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE books ADD CONSTRAINT books_isbn_key UNIQUE (isbn);

ALTER TABLE books ADD CONSTRAINT books_pkey PRIMARY KEY (id);

ALTER TABLE sales ADD CONSTRAINT sales_book_id_fkey FOREIGN KEY (book_id) REFERENCES books(id);

ALTER TABLE sales ADD CONSTRAINT sales_pkey PRIMARY KEY (id);

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX books_isbn_key ON public.books USING btree (isbn)

CREATE UNIQUE INDEX books_pkey ON public.books USING btree (id)

CREATE UNIQUE INDEX sales_pkey ON public.sales USING btree (id)

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

