
--
-- Postgres SQL Schema dump automatic generated by geni
--


-- EXTENSIONS 

CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA public;

-- TABLES 

CREATE TABLE books (
 created_at timestamp with time zone ,
 genre character varying (50),
 id uuid  NOT NULL,
 isbn character varying (13) NOT NULL,
 price numeric  NOT NULL,
 stock_quantity integer ,
 title character varying (255) NOT NULL,
 updated_at timestamp with time zone 
);

CREATE TABLE schema_migrations (
 id character varying (255) NOT NULL
);

-- CONSTRAINTS 

ALTER TABLE books ADD CONSTRAINT books_isbn_key UNIQUE (isbn);

ALTER TABLE books ADD CONSTRAINT books_pkey PRIMARY KEY (id);

ALTER TABLE schema_migrations ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (id);

-- INDEXES 

CREATE UNIQUE INDEX books_isbn_key ON public.books USING btree (isbn)

CREATE UNIQUE INDEX books_pkey ON public.books USING btree (id)

CREATE UNIQUE INDEX schema_migrations_pkey ON public.schema_migrations USING btree (id)

